name: deploy-book-and-doxygen

on:
  push:
    branches:
    - main

jobs:
  deploy-book-and-doxygen:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
    - uses: actions/checkout@v4.1.4

    - name: Set up Python
      uses: actions/setup-python@v5.1.0

    - name: Install dependencies
      run: |
        pip install -U jupyter-book
        # Install Doxygen
        sudo apt-get update && sudo apt-get install -y doxygen

    - name: Cache
      uses: actions/cache@v4
      with:
        path: _build/.jupyter_cache
        key: ${{ runner.os }}-jupyter-book-cache-${{ hashFiles('requirements.txt') }}

    - name: Build the Jupyter Book
      run: |
        jupyter-book build --all warehouse-delivery-network

    - name: Build Doxygen documentation
      run: |
        doxygen Doxyfile

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: book
        path: "warehouse-delivery-network/_build/html"
    
    - name: Upload Doxygen documentation
      uses: actions/upload-artifact@v2
      with:
        name: doxygen
        path: "warehouse-delivery-network/documentation/html"

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v2
      with:
        path: "warehouse-delivery-network/_build/html"
