name: deploy-book

on:
  push:
    branches:
    - main

jobs:
  deploy-book:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
    - uses: actions/checkout@v4.1.4

    - name: Set up Python 5.1
      uses: actions/setup-python@v5.1.0

    - name: Install dependencies
      run: |
        pip install -U jupyter-book

    - name: Cache
      uses: actions/cache@v4.0.2
      with:
        path: _build/.jupyter_cache
        key: jupyter-book-cache-${{ hashFiles('requirements.txt') }}

    - name: Build the book
      run: |
        jupyter-book build --all warehouse-delivery-network

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.3.3
      with:
        path: "warehouse-delivery-network/_build/html"

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4.4.0
      with:
        branch: gh-pages
        folder: warehouse-delivery-network/_build/html
        token: ${{ secrets.GITHUB_TOKEN }}

